name: Build FIT FUN GYM APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil project
        uses: actions/checkout@v4

      - name: Siapkan Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Siapkan Android SDK
        uses: android-actions/setup-android@v3

      - name: Siapkan Android SDK Platform
        run: |
          sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Siapkan Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Build APK
        run: gradle assembleDebug

      - name: Simpan APK
        uses: actions/upload-artifact@v4
        with:
          name: FIT-FUN-GYM-APK
          path: app/build/outputs/apk/debug/app-debug.apk
